---
# Network name
- type: replace
  path: /instance_groups/name=smoke-tests/networks/name=default/name
  value: ((smoke_tests_network))

- type: replace
  path: /instance_groups/name=nats/networks/name=default/name
  value: ((nats_network))

- type: replace
  path: /instance_groups/name=doppler/networks/name=default/name
  value: ((doppler_network))

- type: replace
  path: /instance_groups/name=adapter/networks/name=default/name
  value: ((adapter_network))

- type: replace
  path: /instance_groups/name=database/networks/name=default/name
  value: ((database_network))

- type: replace
  path: /instance_groups/name=diego-api/networks/name=default/name
  value: ((diego_api_network))

- type: replace
  path: /instance_groups/name=uaa/networks/name=default/name
  value: ((uaa_network))

- type: replace
  path: /instance_groups/name=singleton-blobstore/networks/name=default/name
  value: ((singleton_blobstore_network))

- type: replace
  path: /instance_groups/name=api/networks/name=default/name
  value: ((api_network))

- type: replace
  path: /instance_groups/name=cc-worker/networks/name=default/name
  value: ((cc_worker_network))

- type: replace
  path: /instance_groups/name=router/networks/name=default/name
  value: ((router_network))

- type: replace
  path: /instance_groups/name=scheduler/networks/name=default/name
  value: ((scheduler_network))

- type: replace
  path: /instance_groups/name=diego-cell/networks/name=default/name
  value: ((diego_cell_network))

- type: replace
  path: /instance_groups/name=log-api/networks/name=default/name
  value: ((log_api_network))

- type: replace
  path: /instance_groups/name=tcp-router/networks/name=default/name
  value: ((tcp_router_network))

- type: replace
  path: /instance_groups/name=credhub/networks/name=default/name
  value: ((credhub_network))

- type: replace
  path: /instance_groups/name=rotate-cc-database-key/networks/name=default/name
  value: ((rotate_cc_database_key_network))

# Deployment Name
- type: replace
  path: /name
  value: ((deployment_name))

# Bosh DNS Aliases
- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases
  value:
  - domain: '_.cell.service.cf.internal'
    targets:
    - query: '_'
      instance_group: diego-cell
      deployment: ((deployment_name))
      network: ((diego_cell_network))
      domain: bosh
    - query: '_'
      instance_group: windows2012R2-cell
      deployment: ((deployment_name))
      network: ((diego_cell_network))
      domain: bosh
    - query: '_'
      instance_group: windows2016-cell
      deployment: ((deployment_name))
      network: ((diego_cell_network))
      domain: bosh
    - query: '_'
      instance_group: isolated-diego-cell
      deployment: ((deployment_name))
      network: ((diego_cell_network))
      domain: bosh
  - domain: auctioneer.service.cf.internal
    targets:
    - query: '*'
      instance_group: scheduler
      deployment: ((deployment_name))
      network: ((scheduler_network))
      domain: bosh
  - domain: bbs.service.cf.internal
    targets:
    - query: 'q-s4'
      instance_group: diego-api
      deployment: ((deployment_name))
      network: ((diego_api_network))
      domain: bosh
  - domain: bits.service.cf.internal
    targets:
    - query: '*'
      instance_group: bits
      deployment: ((deployment_name))
      network: ((diego_api_network))
      domain: bosh
  - domain: blobstore.service.cf.internal
    targets:
    - query: '*'
      instance_group: singleton-blobstore
      deployment: ((deployment_name))
      network: ((singleton_blobstore_network))
      domain: bosh
  - domain: cc-uploader.service.cf.internal
    targets:
    - query: '*'
      instance_group: api
      deployment: ((deployment_name))
      network: ((api_network))
      domain: bosh
  - domain: cloud-controller-ng.service.cf.internal
    targets:
    - query: '*'
      instance_group: api
      deployment: ((deployment_name))
      network: ((api_network))
      domain: bosh
  - domain: credhub.service.cf.internal
    targets:
    - query: '*'
      instance_group: credhub
      deployment: ((deployment_name))
      network: ((credhub_network))
      domain: bosh
  - domain: doppler.service.cf.internal
    targets:
    - query: '*'
      instance_group: doppler
      deployment: ((deployment_name))
      network: ((doppler_network))
      domain: bosh
  - domain: file-server.service.cf.internal
    targets:
    - query: '*'
      instance_group: api
      deployment: ((deployment_name))
      network: ((api_network))
      domain: bosh
  - domain: gorouter.service.cf.internal
    targets:
    - query: '*'
      instance_group: router
      deployment: ((deployment_name))
      network: ((router_network))
      domain: bosh
  - domain: locket.service.cf.internal
    targets:
    - query: '*'
      instance_group: diego-api
      deployment: ((deployment_name))
      network: ((diego_api_network))
      domain: bosh
  - domain: loggregator-trafficcontroller.service.cf.internal
    targets:
    - query: '*'
      instance_group: log-api
      deployment: ((deployment_name))
      network: ((api_network))
      domain: bosh
  - domain: policy-server.service.cf.internal
    targets:
    - query: '*'
      instance_group: api
      deployment: ((deployment_name))
      network: ((api_network))
      domain: bosh
  - domain: reverse-log-proxy.service.cf.internal
    targets:
    - query: '*'
      instance_group: log-api
      deployment: ((deployment_name))
      network: ((log_api_network))
      domain: bosh
  - domain: routing-api.service.cf.internal
    targets:
    - query: '*'
      instance_group: api
      deployment: ((deployment_name))
      network: ((api_network))
      domain: bosh
  - domain: silk-controller.service.cf.internal
    targets:
    - query: '*'
      instance_group: diego-api
      deployment: ((deployment_name))
      network: ((diego_api_network))
      domain: bosh
  - domain: sql-db.service.cf.internal
    targets:
    - query: '*'
      instance_group: database
      deployment: ((deployment_name))
      network: ((database_network))
      domain: bosh
  - domain: ssh-proxy.service.cf.internal
    targets:
    - query: '*'
      instance_group: scheduler
      deployment: ((deployment_name))
      network: ((scheduler_network))
      domain: bosh
  - domain: tps.service.cf.internal
    targets:
    - query: '*'
      instance_group: scheduler
      deployment: ((deployment_name))
      network: ((scheduler_network))
      domain: bosh
  - domain: uaa.service.cf.internal
    targets:
    - query: '*'
      instance_group: uaa
      deployment: ((deployment_name))
      network: ((uaa_network))
      domain: bosh
